import localFont from "next/font/local";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased no-scroll-bar`}>
        <Header />
        <PageTransition>{children}</PageTransition>
        <StairTransition/>
        <Footer />
      </body>
    </html>
  );
}
